import { definePracticeSet } from "@/types/content";
import { okulDb } from "@/content/databases/okul";

export const altSorgular = definePracticeSet({
  slug: "alt-sorgular",
  baslik: "Alt Sorgular",
  aciklama: "Skaler alt sorgular, IN/EXISTS, türetilmiş tablolar ve ilişkili alt sorgular — okul veritabanı üzerinde.",
  veritabaniId: okulDb.id,
  sorular: [
    {
      id: "pr-sub-1",
      seviye: "Kolay",
      baslik: "Ortalama Üstü Notlar",
      soru: "final_grade'i, tüm final_grade'lerin ortalamasının üzerinde olan kayıtların student_id ve final_grade'ini getiren bir sorgu yaz.",
      ipucu: "WHERE final_grade > (SELECT AVG(final_grade) FROM enrollments) kalıbını kullanabilirsin.",
      cozumSql: "SELECT student_id, final_grade FROM enrollments WHERE final_grade > (SELECT AVG(final_grade) FROM enrollments);",
      mod: "sonuc",
    },
    {
      id: "pr-sub-2",
      seviye: "Kolay",
      baslik: "En Yüksek Not",
      soru: "final_grade'i tüm kayıtlar arasındaki en yüksek nota eşit olan kaydın student_id, course_id ve final_grade'ini getiren bir sorgu yaz.",
      ipucu: "WHERE final_grade = (SELECT MAX(final_grade) FROM enrollments) kalıbını kullanabilirsin.",
      cozumSql: "SELECT student_id, course_id, final_grade FROM enrollments WHERE final_grade = (SELECT MAX(final_grade) FROM enrollments);",
      mod: "sonuc",
    },
    {
      id: "pr-sub-3",
      seviye: "Orta",
      baslik: "Elif Aydın'ın Kayıtları",
      soru: "full_name'i 'Elif Aydın' olan öğrencinin student_id'sini bir alt sorguyla bulup, bu öğrencinin tüm enrollments kayıtlarını getiren bir sorgu yaz.",
      ipucu: "WHERE student_id = (SELECT student_id FROM students WHERE full_name = 'Elif Aydın') kalıbını kullanabilirsin.",
      cozumSql: "SELECT * FROM enrollments WHERE student_id = (SELECT student_id FROM students WHERE full_name = 'Elif Aydın');",
      mod: "sonuc",
    },
    {
      id: "pr-sub-4",
      seviye: "Orta",
      baslik: "Dersi Olan Öğrenciler",
      soru: "En az bir derse kayıtlı olan öğrencilerin full_name'ini EXISTS kullanarak getiren bir sorgu yaz.",
      ipucu: "WHERE EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id = s.student_id) kalıbını kullanabilirsin.",
      cozumSql: "SELECT full_name FROM students s WHERE EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id = s.student_id);",
      mod: "sonuc",
    },
    {
      id: "pr-sub-5",
      seviye: "Orta",
      baslik: "Dersi Olmayan Öğrenciler",
      soru: "Hiç derse kayıtlı olmayan öğrencilerin full_name'ini NOT EXISTS kullanarak getiren bir sorgu yaz.",
      ipucu: "WHERE NOT EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id = s.student_id) kalıbını kullanabilirsin.",
      cozumSql: "SELECT full_name FROM students s WHERE NOT EXISTS (SELECT 1 FROM enrollments e WHERE e.student_id = s.student_id);",
      mod: "sonuc",
    },
    {
      id: "pr-sub-6",
      seviye: "Orta",
      baslik: "Matematik I Öğrencileri",
      soru: "'Matematik I' dersine kayıtlı öğrencilerin full_name'ini IN kullanarak getiren bir sorgu yaz.",
      ipucu: "Önce Matematik I'in course_id'sini bulan bir alt sorgu, sonra enrollments'tan öğrenci id'lerini bulan bir alt sorgu iç içe kullanılabilir: WHERE student_id IN (SELECT student_id FROM enrollments WHERE course_id = (SELECT course_id FROM courses WHERE course_name = 'Matematik I')).",
      cozumSql:
        "SELECT full_name FROM students WHERE student_id IN (SELECT student_id FROM enrollments WHERE course_id = (SELECT course_id FROM courses WHERE course_name = 'Matematik I'));",
      mod: "sonuc",
    },
    {
      id: "pr-sub-7",
      seviye: "Zor",
      baslik: "Ders Şampiyonları",
      soru: "Her dersteki (course_id) en yüksek final_grade'e sahip kaydı/kayıtları (student_id, course_id, final_grade) ilişkili alt sorgu ile getiren bir sorgu yaz.",
      ipucu: "WHERE final_grade = (SELECT MAX(final_grade) FROM enrollments e2 WHERE e2.course_id = e.course_id) kalıbını kullanabilirsin.",
      cozumSql:
        "SELECT student_id, course_id, final_grade FROM enrollments e WHERE final_grade = (SELECT MAX(final_grade) FROM enrollments e2 WHERE e2.course_id = e.course_id);",
      mod: "sonuc",
    },
    {
      id: "pr-sub-8",
      seviye: "Zor",
      baslik: "Ders Ortalamasının Üzerinde",
      soru: "final_grade'i kendi course_id'sinin ortalamasından yüksek olan kayıtların student_id, course_id ve final_grade'ini getiren bir sorgu yaz — türetilmiş tablo kullan.",
      ipucu: "enrollments'ı, course_id bazlı ortalamaları hesaplayan bir alt sorguya course_id üzerinden JOIN'le, sonra WHERE final_grade > ortalama ekle.",
      cozumSql:
        "SELECT e.student_id, e.course_id, e.final_grade FROM enrollments e JOIN (SELECT course_id, AVG(final_grade) AS ortalama FROM enrollments GROUP BY course_id) AS ka ON e.course_id = ka.course_id WHERE e.final_grade > ka.ortalama;",
      mod: "sonuc",
    },
    {
      id: "pr-sub-9",
      seviye: "Zor",
      baslik: "Bağımsız Öğretmenlerin Dersleri",
      soru: "Bir bölüm başkanına bağlı OLMAYAN (kendisi başkan olan, department_head_id IS NULL) öğretmenlerin verdiği derslerin course_name ve teacher_id'sini IN kullanarak getiren bir sorgu yaz.",
      ipucu: "WHERE teacher_id IN (SELECT teacher_id FROM teachers WHERE department_head_id IS NULL) kalıbını kullanabilirsin.",
      cozumSql: "SELECT course_name, teacher_id FROM courses WHERE teacher_id IN (SELECT teacher_id FROM teachers WHERE department_head_id IS NULL);",
      mod: "sonuc",
    },
    {
      id: "pr-sub-10",
      seviye: "Zor",
      baslik: "Yoğun Öğrenciler",
      soru: "En az 2 derse kayıtlı öğrencilerin full_name'ini, bir alt sorgu (GROUP BY + HAVING) ile getiren bir sorgu yaz.",
      ipucu: "WHERE student_id IN (SELECT student_id FROM enrollments GROUP BY student_id HAVING COUNT(*) >= 2) kalıbını kullanabilirsin.",
      cozumSql: "SELECT full_name FROM students WHERE student_id IN (SELECT student_id FROM enrollments GROUP BY student_id HAVING COUNT(*) >= 2);",
      mod: "sonuc",
    },
  ],
});
