import { definePracticeSet } from "@/types/content";
import { kargoDb } from "@/content/databases/kargo";

export const dmlDdl = definePracticeSet({
  slug: "dml-ddl",
  baslik: "DML / DDL",
  aciklama: "INSERT, UPDATE, DELETE, ALTER TABLE, CREATE TABLE ve INDEX — kargo veritabanı üzerinde.",
  veritabaniId: kargoDb.id,
  sorular: [
    {
      id: "pr-dml-1",
      seviye: "Kolay",
      baslik: "Yeni Şube Ekle",
      soru: "branches tablosuna branch_id=7, branch_name='Etimesgut Şube', city='Ankara', opening_date='2025-04-01' değerleriyle yeni bir satır ekleyen bir sorgu yaz.",
      ipucu: "INSERT INTO branches (branch_id, branch_name, city, opening_date) VALUES (...); kalıbını kullanabilirsin.",
      cozumSql: "INSERT INTO branches (branch_id, branch_name, city, opening_date) VALUES (7, 'Etimesgut Şube', 'Ankara', '2025-04-01');",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-2",
      seviye: "Kolay",
      baslik: "Aracı Güncelle",
      soru: "courier_id'si 5 olan kuryenin vehicle_type'ını 'Kamyonet' yapan bir sorgu yaz.",
      ipucu: "UPDATE couriers SET vehicle_type = 'Kamyonet' WHERE courier_id = 5; kalıbını kullanabilirsin.",
      cozumSql: "UPDATE couriers SET vehicle_type = 'Kamyonet' WHERE courier_id = 5;",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-3",
      seviye: "Orta",
      baslik: "İptalleri Sil",
      soru: "status'ü 'İptal' olan tüm gönderileri silen bir sorgu yaz.",
      ipucu: "DELETE FROM shipments WHERE status = 'İptal'; kalıbını kullanabilirsin.",
      cozumSql: "DELETE FROM shipments WHERE status = 'İptal';",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-4",
      seviye: "Orta",
      baslik: "E-posta Sütunu Ekle",
      soru: "couriers tablosuna 'email' adında TEXT tipinde yeni bir sütun ekleyen bir sorgu yaz.",
      ipucu: "ALTER TABLE couriers ADD COLUMN email TEXT; kalıbını kullanabilirsin.",
      cozumSql: "ALTER TABLE couriers ADD COLUMN email TEXT;",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-5",
      seviye: "Orta",
      baslik: "Teslimat Notları Tablosu",
      soru: "'delivery_notes' adında bir tablo oluştur: note_id (INTEGER PRIMARY KEY), shipment_id (INTEGER NOT NULL), note (TEXT NOT NULL).",
      ipucu: "CREATE TABLE delivery_notes (note_id INTEGER PRIMARY KEY, shipment_id INTEGER NOT NULL, note TEXT NOT NULL); kalıbını kullanabilirsin.",
      cozumSql: "CREATE TABLE delivery_notes (note_id INTEGER PRIMARY KEY, shipment_id INTEGER NOT NULL, note TEXT NOT NULL);",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-6",
      seviye: "Zor",
      baslik: "Ağır Gönderileri Beklet",
      soru: "weight_kg'si 5'ten büyük olan gönderilerin status'ünü 'Beklemede' yapan bir sorgu yaz.",
      ipucu: "UPDATE shipments SET status = 'Beklemede' WHERE weight_kg > 5; kalıbını kullanabilirsin.",
      cozumSql: "UPDATE shipments SET status = 'Beklemede' WHERE weight_kg > 5;",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-7",
      seviye: "Zor",
      baslik: "Şube ve Kurye Birlikte",
      soru: "Aynı sorguda iki INSERT yaz: önce branch_id=7, branch_name='Etimesgut Şube', city='Ankara', opening_date='2025-04-01' ile yeni bir şube ekle; sonra courier_id=13, full_name='Ozan Kılıç', branch_id=7, vehicle_type='Motosiklet', hire_date='2025-05-01' ile bu şubeye bir kurye ekle.",
      ipucu: "İki INSERT ifadesini noktalı virgülle ayırarak yaz.",
      cozumSql:
        "INSERT INTO branches (branch_id, branch_name, city, opening_date) VALUES (7, 'Etimesgut Şube', 'Ankara', '2025-04-01'); INSERT INTO couriers (courier_id, full_name, branch_id, vehicle_type, hire_date) VALUES (13, 'Ozan Kılıç', 7, 'Motosiklet', '2025-05-01');",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-8",
      seviye: "Zor",
      baslik: "Durum İndeksi",
      soru: "shipments tablosunda status sütunu üzerinde idx_shipments_status adında bir INDEX oluştur, sonra PRAGMA index_list('shipments'); ile var olduğunu doğrula (aynı sorguda iki ifade).",
      ipucu: "CREATE INDEX idx_shipments_status ON shipments(status); sonra PRAGMA index_list('shipments'); yaz.",
      cozumSql: "CREATE INDEX idx_shipments_status ON shipments(status); PRAGMA index_list('shipments');",
      mod: "sonuc",
    },
    {
      id: "pr-dml-9",
      seviye: "Zor",
      baslik: "Eski Şubeleri Sil",
      soru: "opening_date'i '2020-01-01' tarihinden ÖNCE olan şubeleri silen bir sorgu yaz.",
      ipucu: "DELETE FROM branches WHERE opening_date < '2020-01-01'; kalıbını kullanabilirsin.",
      cozumSql: "DELETE FROM branches WHERE opening_date < '2020-01-01';",
      mod: "tabloDurumu",
    },
    {
      id: "pr-dml-10",
      seviye: "Zor",
      baslik: "Tabloyu Yeniden Adlandır",
      soru: "branches tablosunun adını 'depots' olarak değiştiren bir sorgu yaz.",
      ipucu: "ALTER TABLE branches RENAME TO depots; kalıbını kullanabilirsin.",
      cozumSql: "ALTER TABLE branches RENAME TO depots;",
      mod: "tabloDurumu",
    },
  ],
});
