import { definePracticeSet } from "@/types/content";
import { sehirlerDb } from "@/content/databases/sehirler";

export const filtreleme = definePracticeSet({
  slug: "filtreleme",
  baslik: "Filtreleme",
  aciklama: "WHERE, karşılaştırma operatörleri, LIKE, IN, BETWEEN ve AND/OR/NOT — şehirler veritabanı üzerinde.",
  veritabaniId: sehirlerDb.id,
  sorular: [
    {
      id: "pr-filtre-1",
      seviye: "Kolay",
      baslik: "Kalabalık İller",
      soru: "population'ı 1.000.000'dan fazla olan illerin province'ını getiren bir sorgu yaz.",
      ipucu: "WHERE population > 1000000 kalıbını kullanabilirsin.",
      cozumSql: "SELECT province FROM cities WHERE population > 1000000;",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-2",
      seviye: "Kolay",
      baslik: "Ege Bölgesi",
      soru: "region'ı 'Ege' olan illerin province ve population'ını getiren bir sorgu yaz.",
      ipucu: "WHERE region = 'Ege' kalıbını kullanabilirsin.",
      cozumSql: "SELECT province, population FROM cities WHERE region = 'Ege';",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-3",
      seviye: "Kolay",
      baslik: "Büyükşehir Olmayanlar",
      soru: "is_metropolitan'ı 0 olan (büyükşehir statüsünde OLMAYAN) illerin province'ını getiren bir sorgu yaz.",
      ipucu: "WHERE is_metropolitan = 0 kalıbını kullanabilirsin.",
      cozumSql: "SELECT province FROM cities WHERE is_metropolitan = 0;",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-4",
      seviye: "Orta",
      baslik: "\"A\" ile Başlayanlar",
      soru: "Adı \"A\" harfiyle başlayan illerin province'ını getiren bir sorgu yaz.",
      ipucu: "WHERE province LIKE 'A%' kalıbını kullanabilirsin.",
      cozumSql: "SELECT province FROM cities WHERE province LIKE 'A%';",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-5",
      seviye: "Orta",
      baslik: "Orta Yükseklikteki İller",
      soru: "elevation'ı 1000 ile 1500 arasında (dahil) olan illerin province ve elevation'ını getiren bir sorgu yaz.",
      ipucu: "WHERE elevation BETWEEN 1000 AND 1500 kalıbını kullanabilirsin.",
      cozumSql: "SELECT province, elevation FROM cities WHERE elevation BETWEEN 1000 AND 1500;",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-6",
      seviye: "Orta",
      baslik: "Marmara veya Ege",
      soru: "region'ı 'Marmara' VEYA 'Ege' olan illerin province ve region'ını getiren bir sorgu yaz — IN kullan.",
      ipucu: "WHERE region IN ('Marmara', 'Ege') kalıbını kullanabilirsin.",
      cozumSql: "SELECT province, region FROM cities WHERE region IN ('Marmara', 'Ege');",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-7",
      seviye: "Orta",
      baslik: "Kalabalık Büyükşehirler",
      soru: "population'ı 500.000'den fazla VE is_metropolitan'ı 1 olan illerin province'ını getiren bir sorgu yaz.",
      ipucu: "WHERE population > 500000 AND is_metropolitan = 1 kalıbını kullanabilirsin.",
      cozumSql: "SELECT province FROM cities WHERE population > 500000 AND is_metropolitan = 1;",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-8",
      seviye: "Zor",
      baslik: "Karadeniz Dışı Yükseklikler",
      soru: "region'ı 'Karadeniz' OLMAYAN VE elevation'ı 1000'in üzerinde olan illerin province ve region'ını getiren bir sorgu yaz.",
      ipucu: "WHERE region != 'Karadeniz' AND elevation > 1000 kalıbını kullanabilirsin.",
      cozumSql: "SELECT province, region FROM cities WHERE region != 'Karadeniz' AND elevation > 1000;",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-9",
      seviye: "Zor",
      baslik: "\"Kale\" Geçen İller",
      soru: "Adında \"kale\" geçen illerin province'ını getiren bir sorgu yaz.",
      ipucu: "WHERE province LIKE '%kale%' kalıbını kullanabilirsin.",
      cozumSql: "SELECT province FROM cities WHERE province LIKE '%kale%';",
      mod: "sonuc",
    },
    {
      id: "pr-filtre-10",
      seviye: "Zor",
      baslik: "Uçlardaki İller",
      soru: "population'ı 200.000'in ALTINDA OLAN ya da elevation'ı 2000'in ÜZERİNDE olan illerin province'ını getiren bir sorgu yaz — OR kullan.",
      ipucu: "WHERE population < 200000 OR elevation > 2000 kalıbını kullanabilirsin.",
      cozumSql: "SELECT province FROM cities WHERE population < 200000 OR elevation > 2000;",
      mod: "sonuc",
    },
  ],
});
