import { definePracticeSet } from "@/types/content";
import { filmlerDb } from "@/content/databases/filmler";

export const selectTemelleri = definePracticeSet({
  slug: "select-temelleri",
  baslik: "SELECT Temelleri",
  aciklama: "Sütun seçme, takma ad, DISTINCT, ORDER BY ve LIMIT — filmler veritabanı üzerinde.",
  veritabaniId: filmlerDb.id,
  sorular: [
    {
      id: "pr-select-1",
      seviye: "Kolay",
      baslik: "Film Adı ve Yılı",
      soru: "Tüm filmlerin title ve release_year sütunlarını getiren bir sorgu yaz.",
      ipucu: "SELECT title, release_year FROM movies; kalıbını kullanabilirsin.",
      cozumSql: "SELECT title, release_year FROM movies;",
      mod: "sonuc",
    },
    {
      id: "pr-select-2",
      seviye: "Kolay",
      baslik: "Yönetmenler (Tekrarsız)",
      soru: "Filmlerin yönetmenlerini (director), tekrarsız olarak getiren bir sorgu yaz.",
      ipucu: "SELECT DISTINCT director FROM movies; kalıbını kullanabilirsin.",
      cozumSql: "SELECT DISTINCT director FROM movies;",
      mod: "sonuc",
    },
    {
      id: "pr-select-3",
      seviye: "Kolay",
      baslik: "Takma Adlarla",
      soru: "Filmlerin title'ını film_adi, rating'ini puan takma adlarıyla getiren bir sorgu yaz.",
      ipucu: "SELECT title AS film_adi, rating AS puan FROM movies; kalıbını kullanabilirsin.",
      cozumSql: "SELECT title AS film_adi, rating AS puan FROM movies;",
      mod: "sonuc",
    },
    {
      id: "pr-select-4",
      seviye: "Orta",
      baslik: "Eskiden Yeniye",
      soru: "Filmleri release_year'a göre eskiden yeniye sıralı, title ve release_year sütunlarıyla getiren bir sorgu yaz.",
      ipucu: "ORDER BY release_year ASC kalıbını kullanabilirsin.",
      cozumSql: "SELECT title, release_year FROM movies ORDER BY release_year ASC;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-select-5",
      seviye: "Orta",
      baslik: "En Yüksek Puanlı 5 Film",
      soru: "Puanı (rating) en yüksek 5 filmi, title ve rating ile getiren bir sorgu yaz.",
      ipucu: "ORDER BY rating DESC LIMIT 5 kalıbını kullanabilirsin.",
      cozumSql: "SELECT title, rating FROM movies ORDER BY rating DESC LIMIT 5;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-select-6",
      seviye: "Orta",
      baslik: "Türler (Alfabetik)",
      soru: "Filmlerin türlerini (genre), tekrarsız ve alfabetik sırayla getiren bir sorgu yaz.",
      ipucu: "SELECT DISTINCT genre FROM movies ORDER BY genre ASC; kalıbını kullanabilirsin.",
      cozumSql: "SELECT DISTINCT genre FROM movies ORDER BY genre ASC;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-select-7",
      seviye: "Orta",
      baslik: "Çoklu Sıralama",
      soru: "Filmleri önce genre'a, sonra release_year'a göre (ikisi de artan) sıralı; title, genre ve release_year ile getiren bir sorgu yaz.",
      ipucu: "ORDER BY genre ASC, release_year ASC kalıbını kullanabilirsin.",
      cozumSql: "SELECT title, genre, release_year FROM movies ORDER BY genre ASC, release_year ASC;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-select-8",
      seviye: "Zor",
      baslik: "En Uzun 3 Film",
      soru: "Süresi (duration_min) en uzun 3 filmi, süreye göre çoktan aza sıralı; title ve duration_min ile getiren bir sorgu yaz.",
      ipucu: "ORDER BY duration_min DESC LIMIT 3 kalıbını kullanabilirsin.",
      cozumSql: "SELECT title, duration_min FROM movies ORDER BY duration_min DESC LIMIT 3;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-select-9",
      seviye: "Zor",
      baslik: "İkinciden Dördüncüye",
      soru: "Puana göre en yüksek 4 film arasından, ilkini atlayarak 2., 3. ve 4. sıradaki filmleri (title, rating) getiren bir sorgu yaz — OFFSET kullan.",
      ipucu: "ORDER BY rating DESC LIMIT 3 OFFSET 1 kalıbını kullanabilirsin.",
      cozumSql: "SELECT title, rating FROM movies ORDER BY rating DESC LIMIT 3 OFFSET 1;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-select-10",
      seviye: "Zor",
      baslik: "Saat Cinsinden Süre",
      soru: "Her filmin title'ını ve duration_min'in 60'a bölümünden elde edilen tam saat kısmını (saat olarak) getiren bir sorgu yaz.",
      ipucu: "SELECT title, duration_min / 60 AS saat FROM movies; kalıbını kullanabilirsin — SQLite'ta iki INTEGER'ın bölümü tam sayıya yuvarlanır.",
      cozumSql: "SELECT title, duration_min / 60 AS saat FROM movies;",
      mod: "sonuc",
    },
  ],
});
