import { definePracticeSet } from "@/types/content";
import { eticaretDb } from "@/content/databases/eticaret";

export const toplulastirmaGroupBy = definePracticeSet({
  slug: "toplulastirma-group-by",
  baslik: "Toplulaştırma ve GROUP BY",
  aciklama: "COUNT/SUM/AVG/MIN/MAX, GROUP BY ve HAVING — e-ticaret veritabanı üzerinde.",
  veritabaniId: eticaretDb.id,
  sorular: [
    {
      id: "pr-agg-1",
      seviye: "Kolay",
      baslik: "Ortalama Fiyat",
      soru: "Tüm ürünlerin ortalama fiyatını (ortalama_fiyat olarak) getiren bir sorgu yaz.",
      ipucu: "SELECT AVG(price) AS ortalama_fiyat FROM products; kalıbını kullanabilirsin.",
      cozumSql: "SELECT AVG(price) AS ortalama_fiyat FROM products;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-2",
      seviye: "Kolay",
      baslik: "Müşteri Sayısı",
      soru: "Kaç farklı müşteri olduğunu (musteri_sayisi olarak) getiren bir sorgu yaz.",
      ipucu: "SELECT COUNT(*) AS musteri_sayisi FROM customers; kalıbını kullanabilirsin.",
      cozumSql: "SELECT COUNT(*) AS musteri_sayisi FROM customers;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-3",
      seviye: "Kolay",
      baslik: "Kategori Başına Ürün Sayısı",
      soru: "Her kategorideki ürün sayısını (category, urun_sayisi) getiren bir sorgu yaz.",
      ipucu: "GROUP BY category ile grupla, COUNT(*) kullan.",
      cozumSql: "SELECT category, COUNT(*) AS urun_sayisi FROM products GROUP BY category;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-4",
      seviye: "Orta",
      baslik: "Şehir Başına Müşteri",
      soru: "Her şehirdeki müşteri sayısını (city, musteri_sayisi) getiren ve sonucu çoktan aza sıralayan bir sorgu yaz.",
      ipucu: "GROUP BY city, COUNT(*) AS musteri_sayisi, ORDER BY musteri_sayisi DESC kalıbını kullanabilirsin.",
      cozumSql: "SELECT city, COUNT(*) AS musteri_sayisi FROM customers GROUP BY city ORDER BY musteri_sayisi DESC;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-agg-5",
      seviye: "Orta",
      baslik: "Durum Başına Sipariş",
      soru: "Her sipariş durumundaki (status) sipariş sayısını (status, siparis_sayisi) getiren bir sorgu yaz.",
      ipucu: "GROUP BY status ile grupla.",
      cozumSql: "SELECT status, COUNT(*) AS siparis_sayisi FROM orders GROUP BY status;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-6",
      seviye: "Orta",
      baslik: "Kalabalık Kategoriler",
      soru: "En az 3 ürünü olan kategorileri (category, urun_sayisi) getiren bir sorgu yaz.",
      ipucu: "GROUP BY category HAVING COUNT(*) >= 3 kalıbını kullanabilirsin.",
      cozumSql: "SELECT category, COUNT(*) AS urun_sayisi FROM products GROUP BY category HAVING COUNT(*) >= 3;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-7",
      seviye: "Orta",
      baslik: "Müşteri Başına Sipariş",
      soru: "Her müşterinin customer_id'sini ve toplam sipariş sayısını (siparis_sayisi olarak) getiren bir sorgu yaz.",
      ipucu: "orders tablosunu customer_id'ye göre GROUP BY'la.",
      cozumSql: "SELECT customer_id, COUNT(*) AS siparis_sayisi FROM orders GROUP BY customer_id;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-8",
      seviye: "Zor",
      baslik: "Pahalı Kategoriler",
      soru: "Ortalama fiyatı 800 TL'nin üzerinde olan kategorileri (category, ortalama_fiyat) getiren bir sorgu yaz.",
      ipucu: "GROUP BY category HAVING AVG(price) > 800 kalıbını kullanabilirsin.",
      cozumSql: "SELECT category, AVG(price) AS ortalama_fiyat FROM products GROUP BY category HAVING AVG(price) > 800;",
      mod: "sonuc",
    },
    {
      id: "pr-agg-9",
      seviye: "Zor",
      baslik: "En Çok Satan 3 Ürün",
      soru: "order_items tablosunda toplam satılan adedi (SUM(quantity)) en yüksek 3 ürünün product_id ve toplam_adet'ini getiren bir sorgu yaz.",
      ipucu: "GROUP BY product_id, SUM(quantity) AS toplam_adet, ORDER BY toplam_adet DESC LIMIT 3 kalıbını kullanabilirsin.",
      cozumSql: "SELECT product_id, SUM(quantity) AS toplam_adet FROM order_items GROUP BY product_id ORDER BY toplam_adet DESC LIMIT 3;",
      mod: "sonuc",
      siralamaOnemli: true,
    },
    {
      id: "pr-agg-10",
      seviye: "Zor",
      baslik: "Elektronik Stoku",
      soru: "category'si 'Elektronik' olan ürünlerin toplam stok miktarını (toplam_stok olarak) getiren bir sorgu yaz.",
      ipucu: "WHERE category = 'Elektronik' ile filtrele, SUM(stock_quantity) kullan.",
      cozumSql: "SELECT SUM(stock_quantity) AS toplam_stok FROM products WHERE category = 'Elektronik';",
      mod: "sonuc",
    },
  ],
});
