// Profil sayfasındaki üniversite seçimi için sabit liste — serbest metin
// yerine bilinçli olarak seçildi (bkz. plan): analiz/karşılaştırma
// (üniversiteler arası) güvenilir olsun diye yazım farkı/kısaltma
// karmaşasını baştan engelliyor. YÖK'ün tanıdığı üniversitelerin büyük
// çoğunluğunu kapsar; listede olmayanlar "Diğer"i seçip serbest metin girer.

export interface UniversiteGrubu {
  baslik: string;
  universiteler: string[];
}

export const DIGER_SECENEGI = "Diğer";

export const UNIVERSITE_GRUPLARI: UniversiteGrubu[] = [
  {
    baslik: "Devlet Üniversiteleri",
    universiteler: [
      "Abdullah Gül Üniversitesi",
      "Adıyaman Üniversitesi",
      "Afyon Kocatepe Üniversitesi",
      "Ağrı İbrahim Çeçen Üniversitesi",
      "Akdeniz Üniversitesi",
      "Aksaray Üniversitesi",
      "Amasya Üniversitesi",
      "Anadolu Üniversitesi",
      "Ankara Üniversitesi",
      "Ankara Hacı Bayram Veli Üniversitesi",
      "Ankara Sosyal Bilimler Üniversitesi",
      "Ankara Yıldırım Beyazıt Üniversitesi",
      "Ardahan Üniversitesi",
      "Artvin Çoruh Üniversitesi",
      "Atatürk Üniversitesi",
      "Aydın Adnan Menderes Üniversitesi",
      "Balıkesir Üniversitesi",
      "Bandırma Onyedi Eylül Üniversitesi",
      "Bartın Üniversitesi",
      "Batman Üniversitesi",
      "Bayburt Üniversitesi",
      "Bilecik Şeyh Edebali Üniversitesi",
      "Bingöl Üniversitesi",
      "Bitlis Eren Üniversitesi",
      "Boğaziçi Üniversitesi",
      "Bolu Abant İzzet Baysal Üniversitesi",
      "Burdur Mehmet Akif Ersoy Üniversitesi",
      "Bursa Teknik Üniversitesi",
      "Bursa Uludağ Üniversitesi",
      "Çanakkale Onsekiz Mart Üniversitesi",
      "Çankırı Karatekin Üniversitesi",
      "Çukurova Üniversitesi",
      "Dicle Üniversitesi",
      "Dokuz Eylül Üniversitesi",
      "Düzce Üniversitesi",
      "Ege Üniversitesi",
      "Erciyes Üniversitesi",
      "Erzincan Binali Yıldırım Üniversitesi",
      "Erzurum Teknik Üniversitesi",
      "Eskişehir Osmangazi Üniversitesi",
      "Eskişehir Teknik Üniversitesi",
      "Fırat Üniversitesi",
      "Galatasaray Üniversitesi",
      "Gazi Üniversitesi",
      "Gaziantep Üniversitesi",
      "Gaziosmanpaşa Üniversitesi (Tokat)",
      "Gebze Teknik Üniversitesi",
      "Giresun Üniversitesi",
      "Gümüşhane Üniversitesi",
      "Hacettepe Üniversitesi",
      "Hakkari Üniversitesi",
      "Harran Üniversitesi",
      "Hatay Mustafa Kemal Üniversitesi",
      "Hitit Üniversitesi",
      "Iğdır Üniversitesi",
      "Isparta Uygulamalı Bilimler Üniversitesi",
      "İnönü Üniversitesi",
      "İskenderun Teknik Üniversitesi",
      "İstanbul Üniversitesi",
      "İstanbul Teknik Üniversitesi",
      "İstanbul Üniversitesi-Cerrahpaşa",
      "İzmir Katip Çelebi Üniversitesi",
      "İzmir Yüksek Teknoloji Enstitüsü",
      "Kafkas Üniversitesi",
      "Kahramanmaraş Sütçü İmam Üniversitesi",
      "Karabük Üniversitesi",
      "Karadeniz Teknik Üniversitesi",
      "Karamanoğlu Mehmetbey Üniversitesi",
      "Kastamonu Üniversitesi",
      "Kayseri Üniversitesi",
      "Kırıkkale Üniversitesi",
      "Kırklareli Üniversitesi",
      "Kırşehir Ahi Evran Üniversitesi",
      "Kocaeli Üniversitesi",
      "Konya Teknik Üniversitesi",
      "Kütahya Dumlupınar Üniversitesi",
      "Kütahya Sağlık Bilimleri Üniversitesi",
      "Malatya Turgut Özal Üniversitesi",
      "Manisa Celal Bayar Üniversitesi",
      "Mardin Artuklu Üniversitesi",
      "Marmara Üniversitesi",
      "Mersin Üniversitesi",
      "Middle East Technical University (ODTÜ)",
      "Milli Savunma Üniversitesi",
      "Mimar Sinan Güzel Sanatlar Üniversitesi",
      "Muğla Sıtkı Koçman Üniversitesi",
      "Munzur Üniversitesi",
      "Muş Alparslan Üniversitesi",
      "Necmettin Erbakan Üniversitesi",
      "Nevşehir Hacı Bektaş Veli Üniversitesi",
      "Niğde Ömer Halisdemir Üniversitesi",
      "Ondokuz Mayıs Üniversitesi",
      "Ordu Üniversitesi",
      "Osmaniye Korkut Ata Üniversitesi",
      "Pamukkale Üniversitesi",
      "Recep Tayyip Erdoğan Üniversitesi",
      "Sakarya Üniversitesi",
      "Sakarya Uygulamalı Bilimler Üniversitesi",
      "Samsun Üniversitesi",
      "Sivas Cumhuriyet Üniversitesi",
      "Sivas Bilim ve Teknoloji Üniversitesi",
      "Süleyman Demirel Üniversitesi",
      "Şırnak Üniversitesi",
      "Tekirdağ Namık Kemal Üniversitesi",
      "Trabzon Üniversitesi",
      "Trakya Üniversitesi",
      "Tokat Gaziosmanpaşa Üniversitesi",
      "Tunceli Üniversitesi",
      "Uşak Üniversitesi",
      "Van Yüzüncü Yıl Üniversitesi",
      "Yıldız Teknik Üniversitesi",
      "Yozgat Bozok Üniversitesi",
      "Zonguldak Bülent Ecevit Üniversitesi",
    ],
  },
  {
    baslik: "Vakıf Üniversiteleri",
    universiteler: [
      "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
      "Alanya Üniversitesi",
      "Altınbaş Üniversitesi",
      "Ankara Bilim Üniversitesi",
      "Ankara Medipol Üniversitesi",
      "Antalya Bilim Üniversitesi",
      "Atılım Üniversitesi",
      "Bahçeşehir Üniversitesi",
      "Başkent Üniversitesi",
      "Beykent Üniversitesi",
      "Beykoz Üniversitesi",
      "Bilkent Üniversitesi",
      "Çağ Üniversitesi",
      "Çankaya Üniversitesi",
      "Demiroğlu Bilim Üniversitesi",
      "Doğuş Üniversitesi",
      "Fenerbahçe Üniversitesi",
      "Gelişim Üniversitesi",
      "Hasan Kalyoncu Üniversitesi",
      "İbn Haldun Üniversitesi",
      "İhsan Doğramacı Bilkent Üniversitesi",
      "İstanbul 29 Mayıs Üniversitesi",
      "İstanbul Arel Üniversitesi",
      "İstanbul Aydın Üniversitesi",
      "İstanbul Bilgi Üniversitesi",
      "İstanbul Esenyurt Üniversitesi",
      "İstanbul Galata Üniversitesi",
      "İstanbul Gedik Üniversitesi",
      "İstanbul Gelişim Üniversitesi",
      "İstanbul Kent Üniversitesi",
      "İstanbul Kültür Üniversitesi",
      "İstanbul Medeniyet Üniversitesi",
      "İstanbul Medipol Üniversitesi",
      "İstanbul Nişantaşı Üniversitesi",
      "İstanbul Okan Üniversitesi",
      "İstanbul Rumeli Üniversitesi",
      "İstanbul Sabahattin Zaim Üniversitesi",
      "İstanbul Şehir Üniversitesi",
      "İstanbul Ticaret Üniversitesi",
      "İstanbul Topkapı Üniversitesi",
      "İstinye Üniversitesi",
      "İzmir Bakırçay Üniversitesi",
      "İzmir Ekonomi Üniversitesi",
      "İzmir Tınaztepe Üniversitesi",
      "Kadir Has Üniversitesi",
      "Koç Üniversitesi",
      "KTO Karatay Üniversitesi",
      "Lokman Hekim Üniversitesi",
      "Maltepe Üniversitesi",
      "MEF Üniversitesi",
      "Nuh Naci Yazgan Üniversitesi",
      "Ostim Teknik Üniversitesi",
      "Özyeğin Üniversitesi",
      "Piri Reis Üniversitesi",
      "Sabancı Üniversitesi",
      "Sanko Üniversitesi",
      "TED Üniversitesi",
      "TOBB Ekonomi ve Teknoloji Üniversitesi",
      "Toros Üniversitesi",
      "Türk Hava Kurumu Üniversitesi",
      "Ufuk Üniversitesi",
      "Üsküdar Üniversitesi",
      "Yaşar Üniversitesi",
      "Yeditepe Üniversitesi",
      "Yeni Yüzyıl Üniversitesi",
    ],
  },
];
