import type { ExamQuestion } from "@/types/content";

export const unite2Sinavi: ExamQuestion[] = [
  {
    id: "sinav-2-1",
    uniteId: 2,
    konu: "İfadeler ve Hesaplamalar",
    dersSlug: "ifadeler-ve-hesaplamalar",
    soru: "SELECT price * 1.20 AS kdvli_fiyat FROM products; sorgusu ne hesaplar?",
    secenekler: [
      "Her ürünün fiyatının %20 eksiğini",
      "Her ürünün fiyatına %20 eklenmiş (KDV dahil) halini",
      "Sadece fiyatı 20 TL olan ürünleri",
      "price sütununu kalıcı olarak 1.20 ile çarpıp günceller",
    ],
    dogruIndex: 1,
    aciklama: "price * 1.20, fiyatın %20 fazlasını hesaplar; SELECT içindeki bu ifade veriyi değiştirmez, sadece sonuçta gösterir.",
  },
  {
    id: "sinav-2-2",
    uniteId: 2,
    konu: "NULL ile Çalışmak",
    dersSlug: "null-ile-calismak",
    soru: "SELECT * FROM customers WHERE phone = NULL; sorgusuyla ilgili doğru ifade hangisidir?",
    secenekler: [
      "phone'u NULL olan tüm müşterileri getirir",
      "Hiçbir satır getirmez — NULL karşılaştırması için IS NULL kullanılmalıdır",
      "Hata verir ve sorgu hiç çalışmaz",
      "phone'u boş metin ('') olan müşterileri getirir",
    ],
    dogruIndex: 1,
    aciklama: "= operatörü NULL ile karşılaştırma yapamaz (sonuç UNKNOWN olur); NULL kontrolü için WHERE phone IS NULL kullanılmalıdır.",
  },
  {
    id: "sinav-2-3",
    uniteId: 2,
    konu: "CASE WHEN",
    dersSlug: "case-when",
    soru: "CASE WHEN stock_quantity = 0 THEN 'Tükendi' WHEN stock_quantity < 10 THEN 'Az Kaldı' ELSE 'Stokta' END ifadesi stock_quantity = 5 için ne döner?",
    secenekler: ["'Tükendi'", "'Az Kaldı'", "'Stokta'", "NULL"],
    dogruIndex: 1,
    aciklama: "5, 0'a eşit olmadığı ama 10'dan küçük olduğu için ikinci koşul sağlanır ve 'Az Kaldı' döner.",
  },
  {
    id: "sinav-2-4",
    uniteId: 2,
    konu: "Toplulaştırma Fonksiyonları",
    dersSlug: "toplulastirma-fonksiyonlari",
    soru: "COUNT(*) ile COUNT(phone) arasındaki fark nedir (customers tablosunda phone bazı satırlarda NULL)?",
    secenekler: [
      "Aralarında fark yoktur",
      "COUNT(*) tüm satırları sayar, COUNT(phone) sadece phone'u NULL OLMAYAN satırları sayar",
      "COUNT(phone), COUNT(*)'tan her zaman büyüktür",
      "COUNT(phone) bir söz dizimi hatasıdır",
    ],
    dogruIndex: 1,
    aciklama: "COUNT(*) satır sayısını sayar; COUNT(kolon) ise sadece o kolonun NULL olmadığı satırları sayar.",
  },
  {
    id: "sinav-2-5",
    uniteId: 2,
    konu: "GROUP BY",
    dersSlug: "group-by",
    soru: "Her kategorideki ürün sayısını getiren doğru sorgu hangisidir?",
    secenekler: [
      "SELECT category, COUNT(*) FROM products;",
      "SELECT category, COUNT(*) FROM products GROUP BY category;",
      "SELECT category, COUNT(*) FROM products ORDER BY category;",
      "SELECT category, COUNT(*) FROM products WHERE category;",
    ],
    dogruIndex: 1,
    aciklama: "COUNT(*) gibi bir toplulaştırma fonksiyonunu bir sütunla birlikte kullanmak için GROUP BY zorunludur.",
  },
  {
    id: "sinav-2-6",
    uniteId: 2,
    konu: "HAVING",
    dersSlug: "having",
    soru: "En az 5 siparişi olan müşterileri bulmak için hangi ifade doğrudur?",
    secenekler: [
      "WHERE COUNT(*) >= 5",
      "GROUP BY customer_id HAVING COUNT(*) >= 5",
      "HAVING customer_id >= 5",
      "WHERE customer_id HAVING COUNT(*) >= 5",
    ],
    dogruIndex: 1,
    aciklama: "Toplulaştırma sonucuna göre filtreleme GROUP BY'dan sonra HAVING ile yapılır; WHERE içinde toplulaştırma fonksiyonu kullanılamaz.",
  },
  {
    id: "sinav-2-7",
    uniteId: 2,
    konu: "Sorgunun Çalışma Sırası",
    dersSlug: "sorgunun-calisma-sirasi",
    soru: "SELECT category, AVG(price) AS ortalama FROM products WHERE ortalama > 1000 GROUP BY category; sorgusundaki hata nedir?",
    secenekler: [
      "AVG fonksiyonu products tablosunda kullanılamaz",
      "WHERE, SELECT'ten önce çalıştığı için ortalama alias'ına henüz erişemez — bunun yerine HAVING kullanılmalı",
      "GROUP BY, WHERE'den önce yazılmalıdır",
      "category sütunu GROUP BY ile kullanılamaz",
    ],
    dogruIndex: 1,
    aciklama: "WHERE, çalışma sırasında SELECT'ten önce çalışır; bu yüzden SELECT'te tanımlanan bir alias'ı WHERE içinde kullanamazsın. Doğrusu HAVING AVG(price) > 1000'dir.",
  },
  {
    id: "sinav-2-8",
    uniteId: 2,
    konu: "İfadeler ve Hesaplamalar",
    dersSlug: "ifadeler-ve-hesaplamalar",
    soru: "SELECT full_name || ' - ' || city FROM customers; sorgusundaki || operatörü ne işe yarar?",
    secenekler: ["Bölme işlemi yapar", "Metin birleştirme (concatenation) yapar", "Mantıksal VEYA (OR) işlemi yapar", "Karşılaştırma yapar"],
    dogruIndex: 1,
    aciklama: "SQLite'ta || operatörü, iki metni birbirine birleştirir.",
  },
  {
    id: "sinav-2-9",
    uniteId: 2,
    konu: "NULL ile Çalışmak",
    dersSlug: "null-ile-calismak",
    soru: "COALESCE(phone, 'Belirtilmemiş') ifadesi ne yapar?",
    secenekler: [
      "phone her zaman 'Belirtilmemiş' olarak değiştirilir",
      "phone NULL ise 'Belirtilmemiş' değerini, değilse phone'un kendisini döndürür",
      "phone ile 'Belirtilmemiş' metnini birleştirir",
      "phone sütununu tablodan siler",
    ],
    dogruIndex: 1,
    aciklama: "COALESCE, verilen değerler arasından NULL olmayan ilkini döndürür.",
  },
  {
    id: "sinav-2-10",
    uniteId: 2,
    konu: "Toplulaştırma Fonksiyonları",
    dersSlug: "toplulastirma-fonksiyonlari",
    soru: "Bir kategorideki en pahalı ürünün fiyatını bulmak için hangi fonksiyon kullanılır?",
    secenekler: ["SUM()", "MAX()", "COUNT()", "AVG()"],
    dogruIndex: 1,
    aciklama: "MAX(), bir sütundaki en yüksek değeri bulur.",
  },
  {
    id: "sinav-2-11",
    uniteId: 2,
    konu: "GROUP BY",
    dersSlug: "group-by",
    soru: "GROUP BY category, city ifadesi ne yapar?",
    secenekler: [
      "Sadece category'e göre gruplar, city'i yok sayar",
      "category VE city'nin her benzersiz kombinasyonu için ayrı bir grup oluşturur",
      "Söz dizimi hatasıdır, GROUP BY tek sütun alabilir",
      "Önce category'e göre sıralar, sonra city'e göre filtreler",
    ],
    dogruIndex: 1,
    aciklama: "Birden fazla sütunla GROUP BY, bu sütunların her benzersiz kombinasyonunu ayrı bir grup olarak ele alır.",
  },
  {
    id: "sinav-2-12",
    uniteId: 2,
    konu: "Sorgunun Çalışma Sırası",
    dersSlug: "sorgunun-calisma-sirasi",
    soru: "Bir SELECT sorgusunun mantıksal çalışma sırası aşağıdakilerden hangisidir?",
    secenekler: [
      "SELECT → FROM → WHERE → GROUP BY → HAVING → ORDER BY",
      "FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY",
      "FROM → SELECT → WHERE → GROUP BY → ORDER BY → HAVING",
      "WHERE → FROM → SELECT → GROUP BY → HAVING → ORDER BY",
    ],
    dogruIndex: 1,
    aciklama: "Yazım sırası ile çalışma sırası farklıdır: gerçek sıra FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT şeklindedir.",
  },
];
