import type { ExamQuestion } from "@/types/content";

export const unite1Sinavi: ExamQuestion[] = [
  {
    id: "sinav-1-1",
    uniteId: 1,
    konu: "SELECT Temelleri",
    dersSlug: "select-ile-sutun-secme",
    soru: "SELECT DISTINCT genre FROM movies; sorgusu ne yapar?",
    secenekler: [
      "Tüm filmleri genre sırasına göre listeler",
      "Her genre'dan sadece bir örnek film getirir",
      "genre sütunundaki tekrar eden değerleri kaldırıp benzersiz listesini getirir",
      "Sadece genre sütunu NULL olmayan filmleri getirir",
    ],
    dogruIndex: 2,
    aciklama: "DISTINCT, sonuçtaki tekrar eden değerleri eler; burada genre sütununun tekrarsız listesini verir.",
  },
  {
    id: "sinav-1-2",
    uniteId: 1,
    konu: "WHERE ile Filtreleme",
    dersSlug: "where-ile-filtreleme",
    soru: "'Komedi' türündeki filmleri getiren doğru sorgu hangisidir?",
    secenekler: [
      "SELECT * FROM movies WHERE genre = Komedi;",
      "SELECT * FROM movies WHERE genre = 'Komedi';",
      "SELECT * FROM movies WHERE genre LIKE Komedi;",
      "SELECT * FROM movies WHERE genre != 'Komedi';",
    ],
    dogruIndex: 1,
    aciklama: "Metin değerleri tek tırnak içinde yazılmalıdır; tırnaksız yazımda 'Komedi' bir sütun adı gibi yorumlanıp hata verir. Son seçenek ise tam tersini filtreler.",
  },
  {
    id: "sinav-1-3",
    uniteId: 1,
    konu: "SELECT Temelleri",
    dersSlug: "select-ile-sutun-secme",
    soru: "SELECT title, release_year AS FROM movies; sorgusundaki hata nedir?",
    secenekler: [
      "FROM anahtar kelimesi yanlış yazılmış",
      "AS'tan sonra bir takma ad eksik",
      "title sütunu yoktur",
      "release_year sayısal olduğu için AS ile kullanılamaz",
    ],
    dogruIndex: 1,
    aciklama: "AS, bir takma ad tanımlamak için kullanılır; AS'tan sonra mutlaka bir isim (ör. AS yil) gelmelidir.",
  },
  {
    id: "sinav-1-4",
    uniteId: 1,
    konu: "Metin Arama ve Aralıklar",
    dersSlug: "metin-arama-ve-araliklar",
    soru: "province LIKE '_a%' ifadesi neyi eşleştirir?",
    secenekler: [
      "'a' ile başlayan tüm iller",
      "İkinci harfi 'a' olan iller",
      "İçinde herhangi bir yerde 'a' geçen iller",
      "Sadece tam olarak 'a' harfinden oluşan iller",
    ],
    dogruIndex: 1,
    aciklama: "_ tek bir karakteri temsil eder; '_a%' deseni ikinci harfi 'a' olan metinleri eşleştirir.",
  },
  {
    id: "sinav-1-5",
    uniteId: 1,
    konu: "Metin Arama ve Aralıklar",
    dersSlug: "metin-arama-ve-araliklar",
    soru: "elevation'ı 500 ile 1000 arasında (her iki uç dahil) olan illeri getirmek için hangi sorgu doğrudur?",
    secenekler: [
      "SELECT * FROM cities WHERE elevation > 500 AND elevation < 1000;",
      "SELECT * FROM cities WHERE elevation BETWEEN 500 AND 1000;",
      "SELECT * FROM cities WHERE elevation IN (500, 1000);",
      "SELECT * FROM cities WHERE elevation LIKE '500-1000';",
    ],
    dogruIndex: 1,
    aciklama: "BETWEEN, her iki ucu da dahil ederek aralık filtrelemesi yapar; ilk seçenek 500 ve 1000'i dışarıda bırakır.",
  },
  {
    id: "sinav-1-6",
    uniteId: 1,
    konu: "Sıralama ve Sınırlama",
    dersSlug: "siralama-ve-sinirlama",
    soru: "SELECT title FROM movies ORDER BY rating DESC LIMIT 1; sorgusu ne döndürür?",
    secenekler: [
      "En düşük puanlı filmin adını",
      "En yüksek puanlı filmin adını",
      "Tüm filmlerin adını puana göre sıralı",
      "Rastgele bir filmin adını",
    ],
    dogruIndex: 1,
    aciklama: "ORDER BY rating DESC, puana göre çoktan aza sıralar; LIMIT 1 ile sadece ilk (en yüksek puanlı) satır alınır.",
  },
  {
    id: "sinav-1-7",
    uniteId: 1,
    konu: "Sıralama ve Sınırlama",
    dersSlug: "siralama-ve-sinirlama",
    soru: "SELECT title FROM movies LIMIT 5 ORDER BY release_year; sorgusundaki hata nedir?",
    secenekler: [
      "ORDER BY, LIMIT'ten SONRA değil ÖNCE yazılmalıdır",
      "LIMIT 5 yanlış bir sayıdır",
      "release_year sütunu ORDER BY ile kullanılamaz",
      "Sorguda hiçbir hata yoktur",
    ],
    dogruIndex: 0,
    aciklama: "SQL'de ORDER BY her zaman LIMIT'ten önce yazılır; aksi halde söz dizimi hatası oluşur.",
  },
  {
    id: "sinav-1-8",
    uniteId: 1,
    konu: "Metin Arama ve Aralıklar",
    dersSlug: "metin-arama-ve-araliklar",
    soru: "region'ı 'Ege' veya 'Akdeniz' olan illeri IN kullanarak getiren doğru sorgu hangisidir?",
    secenekler: [
      "SELECT * FROM cities WHERE region IN ('Ege', 'Akdeniz');",
      "SELECT * FROM cities WHERE region IN 'Ege', 'Akdeniz';",
      "SELECT * FROM cities WHERE region = ('Ege', 'Akdeniz');",
      "SELECT * FROM cities WHERE region IN ['Ege', 'Akdeniz'];",
    ],
    dogruIndex: 0,
    aciklama: "IN, parantez içine virgülle ayrılmış bir değer listesi alır: IN ('deger1', 'deger2').",
  },
  {
    id: "sinav-1-9",
    uniteId: 1,
    konu: "WHERE ile Filtreleme",
    dersSlug: "where-ile-filtreleme",
    soru: "WHERE genre = 'Dram' AND rating > 8 OR genre = 'Komedi' ifadesiyle ilgili doğru yorum hangisidir?",
    secenekler: [
      "Puanı 8'den yüksek dram filmlerini VEYA herhangi bir puana sahip komedi filmlerini getirir (AND, OR'dan önce değerlendirilir)",
      "Sadece hem dram hem komedi olan filmleri getirir",
      "AND ve OR aynı önceliğe sahiptir, soldan sağa değerlendirilir",
      "Bu sorgu SQL'de geçersizdir",
    ],
    dogruIndex: 0,
    aciklama: "SQL'de AND, OR'dan önce değerlendirilir; belirsizliği önlemek için parantez kullanmak her zaman daha güvenlidir.",
  },
  {
    id: "sinav-1-10",
    uniteId: 1,
    konu: "Metin Arama ve Aralıklar",
    dersSlug: "metin-arama-ve-araliklar",
    soru: "SELECT title FROM movies WHERE title NOT LIKE '%a%'; sorgusu neyi getirir?",
    secenekler: [
      "Adında 'a' harfi geçen filmleri",
      "Adında hiç 'a' harfi geçmeyen filmleri",
      "Adı 'a' ile biten filmleri",
      "Adı 'a' ile başlamayan filmleri",
    ],
    dogruIndex: 1,
    aciklama: "NOT LIKE '%a%', içinde herhangi bir yerde 'a' geçen metinleri hariç tutar — yani adında hiç 'a' geçmeyenleri getirir.",
  },
  {
    id: "sinav-1-11",
    uniteId: 1,
    konu: "Temel Kavramlar",
    dersSlug: "tekrar-turkiye-turu",
    soru: "SQLite'ta evet/hayır (boolean) değerler genellikle nasıl temsil edilir?",
    secenekler: [
      "Ayrı bir BOOLEAN tipiyle",
      "'evet'/'hayır' metniyle",
      "INTEGER tipinde 1 ve 0 ile",
      "SQLite boolean değerleri desteklemez",
    ],
    dogruIndex: 2,
    aciklama: "SQLite'ta ayrı bir BOOLEAN tipi yoktur; evet/hayır durumları genellikle INTEGER (1/0) ile temsil edilir.",
  },
  {
    id: "sinav-1-12",
    uniteId: 1,
    konu: "SELECT Temelleri",
    dersSlug: "select-ile-sutun-secme",
    soru: "Filmlerin title sütununu film_adi takma adıyla getiren doğru sorgu hangisidir?",
    secenekler: [
      "SELECT title AS film_adi FROM movies;",
      "SELECT title film_adi AS FROM movies;",
      "SELECT AS film_adi title FROM movies;",
      "SELECT title = film_adi FROM movies;",
    ],
    dogruIndex: 0,
    aciklama: "Takma ad söz dizimi: sütun_adı AS takma_ad. Doğru kullanım: title AS film_adi.",
  },
];
