import type { ExamQuestion } from "@/types/content";

export const unite4Sinavi: ExamQuestion[] = [
  {
    id: "sinav-4-1",
    uniteId: 4,
    konu: "Alt Sorgu Temelleri",
    dersSlug: "alt-sorgu-temelleri",
    soru: "= operatörüyle kullanılan bir alt sorgu ne döndürmelidir?",
    secenekler: ["Herhangi sayıda satır", "Tam olarak tek bir satır ve tek bir sütun (skaler değer)", "En az iki satır", "Sadece metin değerleri"],
    dogruIndex: 1,
    aciklama: "= gibi operatörler tek bir değerle karşılaştırma yapar; alt sorgu birden fazla satır döndürürse SQL hata verir.",
  },
  {
    id: "sinav-4-2",
    uniteId: 4,
    konu: "IN / EXISTS",
    dersSlug: "in-exists",
    soru: "Alt sorgunun döndürdüğü listede bir NULL varsa, NOT IN ne yapar?",
    secenekler: ["NULL'ı yok sayar, normal çalışır", "Hiçbir satır döndürmez — klasik bir SQL tuzağı", "Hata verir", "NULL'ı 0 olarak değerlendirir"],
    dogruIndex: 1,
    aciklama: "Listede bir NULL olduğunda NOT IN'in karşılaştırması UNKNOWN olur ve sorgu hiçbir satır döndürmez.",
  },
  {
    id: "sinav-4-3",
    uniteId: 4,
    konu: "IN / EXISTS",
    dersSlug: "in-exists",
    soru: "EXISTS neyle ilgilenir?",
    secenekler: ["Alt sorgunun döndürdüğü değerlerin içeriğiyle", "Sadece alt sorgunun en az bir satır döndürüp döndürmediğiyle", "Alt sorgunun kaç sütun döndürdüğüyle", "Alt sorgunun ne kadar sürede çalıştığıyla"],
    dogruIndex: 1,
    aciklama: "EXISTS, alt sorgunun döndürdüğü değerlerle değil, sadece satır olup olmadığıyla ilgilenir.",
  },
  {
    id: "sinav-4-4",
    uniteId: 4,
    konu: "FROM'da Alt Sorgu ve Correlated",
    dersSlug: "alt-sorgu-from-ve-iliskili",
    soru: "FROM içinde kullanılan bir alt sorgu (türetilmiş tablo) için ne zorunludur?",
    secenekler: ["Hiçbir şey", "Mutlaka bir takma ad verilmesi", "Sadece tek bir sütun döndürmesi", "WHERE koşulu içermemesi"],
    dogruIndex: 1,
    aciklama: "FROM içindeki bir alt sorgu bir tablo gibi davranır ve ona referans verebilmek için mutlaka bir takma ad gerekir.",
  },
  {
    id: "sinav-4-5",
    uniteId: 4,
    konu: "FROM'da Alt Sorgu ve Correlated",
    dersSlug: "alt-sorgu-from-ve-iliskili",
    soru: "İlişkili (correlated) bir alt sorgu, bağımsız bir alt sorgudan nasıl farklıdır?",
    secenekler: ["Farkı yoktur", "Dıştaki sorgunun o anki satırına bir sütun referansıyla bağlıdır", "Sadece INSERT ile kullanılabilir", "Her zaman FROM içinde yazılır"],
    dogruIndex: 1,
    aciklama: "İlişkili alt sorgu, dış sorgudaki bir tabloya (ör. p.category) referans verir; bu bağ sonucu dış sorgunun her satırına göre değiştirir.",
  },
  {
    id: "sinav-4-6",
    uniteId: 4,
    konu: "Pencere Fonksiyonları I",
    dersSlug: "pencere-fonksiyonlari-1",
    soru: "İki satır aynı değere sahipse, RANK() ile DENSE_RANK() arasındaki fark nedir?",
    secenekler: ["Fark yoktur", "RANK eşitlikten sonraki sırayı atlar (1,2,2,4); DENSE_RANK atlamaz (1,2,2,3)", "DENSE_RANK sırayı atlar, RANK atlamaz", "RANK sadece metinlerde çalışır"],
    dogruIndex: 1,
    aciklama: "RANK, eşit değerlere aynı sırayı verip sonraki sırayı atlar; DENSE_RANK atlama yapmaz.",
  },
  {
    id: "sinav-4-7",
    uniteId: 4,
    konu: "Pencere Fonksiyonları I",
    dersSlug: "pencere-fonksiyonlari-1",
    soru: "PARTITION BY, OVER() içinde ne işe yarar?",
    secenekler: ["Satırları filtreler (WHERE gibi)", "Satırları belirtilen sütuna göre gruplara ayırır; her grup için hesaplama sıfırdan başlar", "Sonucu genel olarak sıralar", "Bir tabloyu ikiye böler"],
    dogruIndex: 1,
    aciklama: "PARTITION BY, GROUP BY'a benzer şekilde satırları gruplara ayırır ama satırları tek tek korur.",
  },
  {
    id: "sinav-4-8",
    uniteId: 4,
    konu: "Pencere Fonksiyonları I",
    dersSlug: "pencere-fonksiyonlari-1",
    soru: "Bir pencere fonksiyonunun sonucuna göre satırları filtrelemek istediğinde ne yapman gerekir?",
    secenekler: ["Doğrudan WHERE içinde kullanabilirsin", "Bir alt sorguda hesaplayıp dış sorguda WHERE ile filtrelemen gerekir", "Bu mümkün değildir", "HAVING kullanman yeterlidir, WHERE gerekmez"],
    dogruIndex: 1,
    aciklama: "WHERE, pencere fonksiyonlarından önce çalıştığı için onları doğrudan filtreleyemez.",
  },
  {
    id: "sinav-4-9",
    uniteId: 4,
    konu: "Pencere Fonksiyonları II",
    dersSlug: "pencere-fonksiyonlari-2",
    soru: "LAG(order_date) OVER (ORDER BY order_date) ifadesi bir grubun ilk satırında ne döndürür?",
    secenekler: ["0", "NULL — çünkü ondan önceki bir satır yoktur", "Kendi order_date değerini", "Hata verir"],
    dogruIndex: 1,
    aciklama: "İlk satırın 'önceki'si olmadığı için LAG, o satırda NULL döndürür.",
  },
  {
    id: "sinav-4-10",
    uniteId: 4,
    konu: "Pencere Fonksiyonları II",
    dersSlug: "pencere-fonksiyonlari-2",
    soru: "SUM(quantity) OVER (ORDER BY item_id) ifadesi her satırda ne hesaplar?",
    secenekler: ["Sadece o satırın quantity'sini", "Tüm tablodaki toplam quantity'yi (her satırda aynı)", "O satıra kadar (kendisi dahil) birikimli toplamı (yürüyen toplam)", "Bir sonraki satırın quantity'sini"],
    dogruIndex: 2,
    aciklama: "ORDER BY ile kullanılan bir toplulaştırma penceresi, varsayılan olarak 'baştan şu satıra kadar' birikimli bir toplam hesaplar.",
  },
  {
    id: "sinav-4-11",
    uniteId: 4,
    konu: "Alt Sorgu Temelleri",
    dersSlug: "alt-sorgu-temelleri",
    soru: "'Caner Şahin' adlı müşterinin siparişlerini getiren doğru sorgu hangisidir?",
    secenekler: [
      "SELECT * FROM orders WHERE customer_id = (SELECT customer_id FROM customers WHERE full_name = 'Caner Şahin');",
      "SELECT * FROM orders WHERE customer_id = 'Caner Şahin';",
      "SELECT * FROM orders WHERE full_name = 'Caner Şahin';",
      "SELECT * FROM customers WHERE customer_id = (SELECT * FROM orders);",
    ],
    dogruIndex: 0,
    aciklama: "Önce alt sorguyla ismin customer_id'si bulunur, sonra bu id ile orders filtrelenir; orders tablosunda full_name sütunu yoktur.",
  },
  {
    id: "sinav-4-12",
    uniteId: 4,
    konu: "IN / EXISTS",
    dersSlug: "in-exists",
    soru: "NULL tuzağı söz konusu olduğunda NOT IN yerine ne tercih edilir?",
    secenekler: ["NOT EXISTS — NULL'lardan etkilenmez", "UNION", "GROUP BY", "Hiçbiri, tuzaktan kaçmanın yolu yoktur"],
    dogruIndex: 0,
    aciklama: "NOT EXISTS satır varlığını kontrol ettiği için (değer karşılaştırması yapmadığı için) NOT IN'deki NULL tuzağına düşmez.",
  },
];
