import type { ExamQuestion } from "@/types/content";

export const unite3Sinavi: ExamQuestion[] = [
  {
    id: "sinav-3-1",
    uniteId: 3,
    konu: "İlişkisel Model",
    dersSlug: "iliskisel-model",
    soru: "players.team_id sütunu ne tür bir ilişkiyi temsil eder?",
    secenekler: ["Bir Primary Key", "teams tablosuna işaret eden bir Foreign Key", "Bir INDEX", "Bir CHECK kısıtı"],
    dogruIndex: 1,
    aciklama: "players.team_id, teams tablosunun birincil anahtarına işaret eden bir Foreign Key'dir.",
  },
  {
    id: "sinav-3-2",
    uniteId: 3,
    konu: "INNER JOIN",
    dersSlug: "inner-join",
    soru: "INNER JOIN hangi satırları sonuca dahil eder?",
    secenekler: [
      "Sol tablodaki tüm satırları, eşleşme olmasa bile",
      "Sadece her iki tabloda da ON koşulunu sağlayan satırları",
      "Sağ tablodaki tüm satırları",
      "İki tablonun kartezyen çarpımını her zaman",
    ],
    dogruIndex: 1,
    aciklama: "INNER JOIN, sadece ON koşulunu sağlayan (eşleşen) satırları getirir.",
  },
  {
    id: "sinav-3-3",
    uniteId: 3,
    konu: "INNER JOIN",
    dersSlug: "inner-join",
    soru: "SELECT p.full_name, t.team_name FROM players p, teams t; sorgusuyla ilgili en büyük risk nedir?",
    secenekler: [
      "Söz dizimi hatası verir, hiç çalışmaz",
      "ON koşulu olmadığı için kartezyen çarpım oluşur — her oyuncu her takımla eşleşir",
      "Sadece takım adı olmayan oyuncuları getirir",
      "team_name sütunu bulunamaz hatası verir",
    ],
    dogruIndex: 1,
    aciklama: "Virgülle ayrılmış tablolar arasında ON koşulu belirtilmezse SQL, iki tablonun kartezyen çarpımını üretir.",
  },
  {
    id: "sinav-3-4",
    uniteId: 3,
    konu: "LEFT JOIN",
    dersSlug: "left-join",
    soru: "Hiç gol atmamış oyuncuları bulmak için hangi desen kullanılır?",
    secenekler: [
      "INNER JOIN + WHERE goal_id IS NOT NULL",
      "LEFT JOIN + WHERE goal_id IS NULL (anti-join)",
      "RIGHT JOIN + ORDER BY",
      "UNION ALL",
    ],
    dogruIndex: 1,
    aciklama: "LEFT JOIN, eşleşmesi olmayan satırlarda sağ tablo sütunlarını NULL yapar; WHERE ... IS NULL ile bu satırlar (anti-join) filtrelenir.",
  },
  {
    id: "sinav-3-5",
    uniteId: 3,
    konu: "Self JOIN",
    dersSlug: "self-join",
    soru: "Self JOIN yaparken takma ad (alias) kullanmak neden zorunludur?",
    secenekler: [
      "Zorunlu değildir, stil tercihidir",
      "Aynı tablo iki kez FROM'da geçtiği için sütun kökeni belirsizleşir",
      "Takma ad sorguyu otomatik hızlandırır",
      "SQLite takma adsız self join'i reddeder",
    ],
    dogruIndex: 1,
    aciklama: "Aynı tablo sorguda iki kez yer aldığında, farklı takma adlar bu belirsizliği ortadan kaldırır.",
  },
  {
    id: "sinav-3-6",
    uniteId: 3,
    konu: "Çok Tablolu Sorgular",
    dersSlug: "cok-tablolu-sorgular",
    soru: "Üç tabloyu (enrollments, students, courses) zincirleme JOIN'lerken sıralama sonucu değiştirir mi?",
    secenekler: [
      "Evet, JOIN sırası her zaman farklı sonuç üretir",
      "Hayır, SQL hangi tabloların nasıl bağlandığını ON koşullarından anlar",
      "Sadece 3'ten fazla tabloda önemlidir",
      "JOIN sırası performansı değil sonucu etkiler",
    ],
    dogruIndex: 1,
    aciklama: "SQL, JOIN'lerin mantıksal sırasını ON koşullarından çıkarır; yazım sırası genellikle sonucu değiştirmez.",
  },
  {
    id: "sinav-3-7",
    uniteId: 3,
    konu: "Küme İşlemleri",
    dersSlug: "kume-islemleri",
    soru: "UNION ile UNION ALL arasındaki fark nedir?",
    secenekler: [
      "Aralarında fark yoktur",
      "UNION tekrar eden satırları eler, UNION ALL elemez",
      "UNION ALL sadece sayısal sütunlarla çalışır",
      "UNION sadece iki tablo JOIN'lendiğinde kullanılabilir",
    ],
    dogruIndex: 1,
    aciklama: "UNION otomatik olarak DISTINCT uygular; UNION ALL tüm satırları tekrarlarıyla birlikte tutar.",
  },
  {
    id: "sinav-3-8",
    uniteId: 3,
    konu: "Küme İşlemleri",
    dersSlug: "kume-islemleri",
    soru: "SELECT player_id FROM players EXCEPT SELECT player_id FROM goals; sorgusu neyi bulur?",
    secenekler: [
      "Hem players hem goals'ta olan oyuncuları",
      "goals'ta olan ama players'ta olmayan oyuncuları",
      "players'ta olan ama goals'ta hiç geçmeyen oyuncuları (hiç gol atmamış)",
      "Tüm oyuncuları tekrarsız",
    ],
    dogruIndex: 2,
    aciklama: "EXCEPT, birinci sorgunun sonucundan ikinci sorguda da bulunanları çıkarır — burada hiç gol atmamış oyuncuları verir.",
  },
  {
    id: "sinav-3-9",
    uniteId: 3,
    konu: "LEFT JOIN",
    dersSlug: "left-join",
    soru: "LEFT JOIN sonrası GROUP BY ile sayım yaparken COUNT(*) yerine neden COUNT(sağ_tablo.kolon) tercih edilir?",
    secenekler: [
      "Aralarında fark yoktur",
      "COUNT(*), eşleşmesi olmayan satırı da 1 sayar; COUNT(kolon) NULL'ları saymaz, doğru 0 verir",
      "COUNT(*) sadece INNER JOIN ile çalışır",
      "COUNT(kolon) her zaman yanlış sonuç verir",
    ],
    dogruIndex: 1,
    aciklama: "LEFT JOIN'den gelen eşleşmeyen bir satırda COUNT(*) yine de 1 sayar; COUNT(sağ_tablo.kolon) NULL olduğu için doğru şekilde 0 sayar.",
  },
  {
    id: "sinav-3-10",
    uniteId: 3,
    konu: "INNER JOIN",
    dersSlug: "inner-join",
    soru: "Aynı tabloyu (teams) hem ev sahibi hem deplasman için kullanan doğru JOIN yaklaşımı hangisidir?",
    secenekler: [
      "teams tablosunu iki farklı takma adla iki kez JOIN'lemek",
      "teams tablosunu bir kez JOIN'leyip WHERE ile filtrelemek",
      "Bu senaryo SQL'de desteklenmez",
      "UNION ile iki ayrı sorgu birleştirmek zorunludur",
    ],
    dogruIndex: 0,
    aciklama: "Bir tabloyu farklı FK sütunları üzerinden birden fazla kez kullanmak için, her JOIN'e farklı bir takma ad vermek gerekir.",
  },
  {
    id: "sinav-3-11",
    uniteId: 3,
    konu: "Self JOIN",
    dersSlug: "self-join",
    soru: "teachers tablosunda department_head_id NULL olan bir öğretmen ne anlama gelir?",
    secenekler: [
      "Veri hatası, düzeltilmelidir",
      "O öğretmenin bağlı olduğu bir bölüm başkanı yoktur — muhtemelen kendisi başkandır",
      "O öğretmen sistemden silinmiştir",
      "department_head_id hiçbir zaman NULL olamaz",
    ],
    dogruIndex: 1,
    aciklama: "department_head_id NULL olduğunda, o öğretmenin bağlı olduğu bir üst yoktur — bu veri setinde bölüm başkanlarını temsil eder.",
  },
  {
    id: "sinav-3-12",
    uniteId: 3,
    konu: "Çok Tablolu Sorgular",
    dersSlug: "cok-tablolu-sorgular",
    soru: "Çok tablolu bir JOIN'de eksik ya da yanlış bir ON koşulunun en tipik belirtisi nedir?",
    secenekler: [
      "Sorgu her zaman hata verir",
      "Beklenenden çok daha fazla (anlamsız) satır dönmesi",
      "Sonuç her zaman boş döner",
      "SQLite otomatik doğru koşulu tahmin eder",
    ],
    dogruIndex: 1,
    aciklama: "Eksik/yanlış bir ON koşulu genellikle sorguyu hatasız çalıştırır ama kartezyen çarpıma yakın, beklenenden çok daha fazla satır üretir.",
  },
];
