import type { ExamQuestion } from "@/types/content";

export const unite5Sinavi: ExamQuestion[] = [
  {
    id: "sinav-5-1",
    uniteId: 5,
    konu: "INSERT",
    dersSlug: "insert",
    soru: "Tek bir INSERT ifadesiyle birden fazla satır eklemek için ne yapılır?",
    secenekler: ["Mümkün değildir, her satır için ayrı INSERT gerekir", "VALUES'tan sonra birden fazla parantez grubu virgülle ayrılır", "INSERT MULTIPLE anahtar kelimesi kullanılır", "WHERE'e birden fazla değer yazılır"],
    dogruIndex: 1,
    aciklama: "VALUES (a, b), (c, d); şeklinde birden fazla parantez grubu yazarak tek ifadeyle çoklu satır eklenir.",
  },
  {
    id: "sinav-5-2",
    uniteId: 5,
    konu: "UPDATE",
    dersSlug: "update",
    soru: "UPDATE shipments SET status = 'İptal'; (WHERE'siz) çalıştırırsan ne olur?",
    secenekler: ["Hiçbir şey olmaz", "Tablodaki TÜM satırların status'ü 'İptal' olur", "Sadece ilk satır güncellenir", "Sadece zaten 'İptal' olan satırlar etkilenir"],
    dogruIndex: 1,
    aciklama: "WHERE koşulu olmayan bir UPDATE, tablodaki her satırı günceller — en yıkıcı SQL hatalarından biridir.",
  },
  {
    id: "sinav-5-3",
    uniteId: 5,
    konu: "DELETE",
    dersSlug: "delete",
    soru: "DELETE FROM tablo WHERE koşul; ile DROP TABLE tablo; arasındaki fark nedir?",
    secenekler: ["Fark yoktur", "DELETE sadece koşulu sağlayan satırları siler (tablo kalır); DROP TABLE tüm tabloyu yapısıyla siler", "DROP TABLE sadece verileri siler, tabloyu korur", "DELETE WHERE olmadan hiç çalışmaz"],
    dogruIndex: 1,
    aciklama: "DELETE satır düzeyinde çalışır ve tablo yapısını korur; DROP TABLE tabloyu tamamen ortadan kaldırır.",
  },
  {
    id: "sinav-5-4",
    uniteId: 5,
    konu: "CREATE TABLE ve Kısıtlar",
    dersSlug: "create-table-ve-kisitlar",
    soru: "CHECK (score BETWEEN 1 AND 5) kısıtı ne işe yarar?",
    secenekler: ["score sütununu otomatik 1 yapar", "score sütununun sadece 1-5 arasında değer almasını zorunlu kılar", "score sütununu siler", "Hiçbir işlevi yoktur, sadece dokümantasyon amaçlıdır"],
    dogruIndex: 1,
    aciklama: "CHECK, belirtilen koşulu sağlamayan değerlerin o sütuna girilmesini SQL seviyesinde engeller.",
  },
  {
    id: "sinav-5-5",
    uniteId: 5,
    konu: "CREATE TABLE ve Kısıtlar",
    dersSlug: "create-table-ve-kisitlar",
    soru: "UNIQUE ile PRIMARY KEY arasındaki temel fark nedir?",
    secenekler: ["Fark yoktur", "Bir tabloda birden fazla UNIQUE sütun olabilir ama genelde tek bir PRIMARY KEY olur", "UNIQUE sadece metin sütunlarında kullanılır", "PRIMARY KEY NULL'a izin verir, UNIQUE vermez"],
    dogruIndex: 1,
    aciklama: "PRIMARY KEY bir satırı benzersiz tanımlar; UNIQUE herhangi bir sütunun tekrar etmemesini sağlar ve birden fazla UNIQUE sütun olabilir.",
  },
  {
    id: "sinav-5-6",
    uniteId: 5,
    konu: "ALTER ve DROP",
    dersSlug: "alter-ve-drop",
    soru: "ALTER TABLE couriers ADD COLUMN phone TEXT; çalıştırdığında var olan satırlarda phone ne olur?",
    secenekler: ["Boş metin ('')", "NULL (DEFAULT belirtilmediyse)", "0", "Sorgu hata verir, var olan satırlar güncellenemez"],
    dogruIndex: 1,
    aciklama: "Yeni eklenen bir sütun, DEFAULT belirtilmediyse var olan tüm satırlarda NULL değeriyle başlar.",
  },
  {
    id: "sinav-5-7",
    uniteId: 5,
    konu: "ALTER ve DROP",
    dersSlug: "alter-ve-drop",
    soru: "DROP TABLE çalıştırmadan önce neden dikkatli olunmalıdır?",
    secenekler: ["Bu işlem geri alınamaz — tablo yapısı ve verisiyle kalıcı olarak kaybolur", "DROP TABLE her zaman hata verir", "Hiçbir özel dikkat gerekmez, tamamen güvenlidir", "Sadece test ortamlarında çalışır"],
    dogruIndex: 0,
    aciklama: "DROP TABLE geri dönüşü olmayan bir işlemdir; yanlışlıkla çalıştırmak telafisi zor veri kayıplarına yol açabilir.",
  },
  {
    id: "sinav-5-8",
    uniteId: 5,
    konu: "VIEW ve INDEX",
    dersSlug: "view-ve-index",
    soru: "Bir VIEW, verideki değişiklikleri anlık olarak yansıtır mı?",
    secenekler: ["Hayır, oluşturulduğu andaki veriyi donmuş halde saklar", "Evet — VIEW veri kopyalamaz, sorgulandığında altındaki SELECT yeniden çalışır", "Sadece günde bir kez günceller", "VIEW'ler hiçbir zaman güncel veri göstermez"],
    dogruIndex: 1,
    aciklama: "VIEW, bir sorguya verilen kalıcı bir isimdir; veri kopyalamaz, her sorgulandığında altındaki SELECT anlık olarak yeniden çalışır.",
  },
  {
    id: "sinav-5-9",
    uniteId: 5,
    konu: "VIEW ve INDEX",
    dersSlug: "view-ve-index",
    soru: "Her sütuna INDEX eklemek neden iyi bir fikir değildir?",
    secenekler: ["SQLite birden fazla index'e izin vermez", "Her INDEX, INSERT/UPDATE/DELETE işlemlerini yavaşlatır ve disk alanı kaplar", "INDEX'ler 24 saat sonra otomatik silinir", "INDEX eklemek SELECT sorgularını yavaşlatır"],
    dogruIndex: 1,
    aciklama: "Her INDEX'in bir bakım maliyeti vardır — yazma işlemlerinde index de güncellenmesi gerekir.",
  },
  {
    id: "sinav-5-10",
    uniteId: 5,
    konu: "SQL Injection'a Giriş",
    dersSlug: "sql-injection-giris",
    soru: "SQL injection saldırısının temel nedeni nedir?",
    secenekler: ["SQLite'ın eski bir sürüm olması", "Kullanıcı girdisinin doğrulanmadan doğrudan SQL sorgu metnine birleştirilmesi", "Veritabanında çok fazla tablo olması", "INDEX kullanılmaması"],
    dogruIndex: 1,
    aciklama: "SQL injection, kullanıcıdan gelen bir metnin ham haliyle SQL sorgusuna eklenip SQL kodu gibi yorumlanmasından kaynaklanır.",
  },
  {
    id: "sinav-5-11",
    uniteId: 5,
    konu: "SQL Injection'a Giriş",
    dersSlug: "sql-injection-giris",
    soru: "Parametreli sorgular (prepared statements) SQL injection'ı nasıl önler?",
    secenekler: ["Kullanıcı girdisini yasaklayarak", "Kullanıcı girdisini her zaman düz veri olarak ele alır, asla SQL kodu olarak yorumlamaz", "Veritabanını şifreleyerek", "Sadece sayısal girdilere izin vererek"],
    dogruIndex: 1,
    aciklama: "Parametreli sorgularda kullanıcı girdisi sorgu metnine hiç karışmaz; ayrı bir kanaldan 'değer' olarak bağlanır.",
  },
  {
    id: "sinav-5-12",
    uniteId: 5,
    konu: "DELETE",
    dersSlug: "delete",
    soru: "SQLite'ta TRUNCATE TABLE komutu var mıdır?",
    secenekler: ["Evet, MySQL ile birebir aynı şekilde çalışır", "Hayır — SQLite'ta bu komut yoktur; aynı işi WHERE'siz DELETE FROM tablo; görür", "Evet ama sadece AUTOINCREMENT tablolarında", "Hayır, SQLite'ta hiçbir veri silinemez"],
    dogruIndex: 1,
    aciklama: "TRUNCATE, MySQL/PostgreSQL gibi veritabanlarına özgüdür; SQLite'ta yoktur, WHERE'siz DELETE aynı sonucu verir.",
  },
];
