import { defineFunctionRef } from "@/types/content";
import { bosDb } from "@/content/databases/bos";

export const metinFonksiyonlari = [
  defineFunctionRef({
    slug: "length",
    ad: "LENGTH",
    kategori: "Metin",
    sozDizimi: "LENGTH(metin)",
    aciklama: "Bir metnin karakter sayısını döndürür.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT LENGTH('SQL Atölyesi');",
    digerVeritabanlari: "MySQL/SQL Server'da da LENGTH() aynı şekilde çalışır (SQL Server'da LEN() de kullanılabilir).",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "substr",
    ad: "SUBSTR",
    kategori: "Metin",
    sozDizimi: "SUBSTR(metin, baslangic, uzunluk)",
    aciklama: "Bir metnin belirtilen konumundan başlayarak belirtilen uzunlukta bir parçasını döndürür. baslangic 1'den başlar; uzunluk verilmezse sona kadar devam eder. Negatif baslangic, sondan sayar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT SUBSTR('SQL Atölyesi', 1, 3), SUBSTR('SQL Atölyesi', 5);",
    digerVeritabanlari: "MySQL'de SUBSTRING() de kullanılabilir; SQL Server'da sadece SUBSTRING() vardır (SUBSTR yok).",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "upper",
    ad: "UPPER",
    kategori: "Metin",
    sozDizimi: "UPPER(metin)",
    aciklama:
      "Metni büyük harfe çevirir. DİKKAT: SQLite'ın UPPER/LOWER fonksiyonları sadece ASCII karakterleri tanır — Türkçe 'ı' harfi 'I'ya, 'i' harfi 'İ'ye dönüşmez (İngilizce kurallarla çalışır).",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT UPPER('istanbul'), UPPER('ışık');",
    ornekAciklama: "İkinci sonuçta 'ı' harfinin büyümediğini (İngilizce ASCII kuralı) fark et.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "lower",
    ad: "LOWER",
    kategori: "Metin",
    sozDizimi: "LOWER(metin)",
    aciklama: "Metni küçük harfe çevirir. Aynı ASCII sınırlaması UPPER için de geçerlidir.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT LOWER('İSTANBUL');",
    ornekAciklama: "'İ' harfinin küçültülmüş hali beklediğin gibi 'i' olmayabilir — ASCII sınırlaması burada da geçerli.",
  }),
  defineFunctionRef({
    slug: "trim",
    ad: "TRIM",
    kategori: "Metin",
    sozDizimi: "TRIM(metin, [karakterler])",
    aciklama: "Metnin başındaki ve sonundaki boşlukları (ya da ikinci argümanla belirttiğin karakterleri) temizler.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT '[' || TRIM('   SQL Atölyesi   ') || ']';",
  }),
  defineFunctionRef({
    slug: "ltrim",
    ad: "LTRIM",
    kategori: "Metin",
    sozDizimi: "LTRIM(metin)",
    aciklama: "Metnin sadece SOLUNDAKİ boşlukları temizler.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT '[' || LTRIM('   SQL Atölyesi   ') || ']';",
  }),
  defineFunctionRef({
    slug: "rtrim",
    ad: "RTRIM",
    kategori: "Metin",
    sozDizimi: "RTRIM(metin)",
    aciklama: "Metnin sadece SAĞINDAKİ boşlukları temizler.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT '[' || RTRIM('   SQL Atölyesi   ') || ']';",
  }),
  defineFunctionRef({
    slug: "replace",
    ad: "REPLACE",
    kategori: "Metin",
    sozDizimi: "REPLACE(metin, eski, yeni)",
    aciklama: "Metindeki 'eski' değerinin TÜM geçtiği yerleri 'yeni' ile değiştirir.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT REPLACE('2025-01-15', '-', '/');",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "instr",
    ad: "INSTR",
    kategori: "Metin",
    sozDizimi: "INSTR(metin, aranan)",
    aciklama: "Aranan metnin, ana metin içinde İLK geçtiği konumu (1'den başlayarak) döndürür; bulunamazsa 0 döner.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT INSTR('SQL Atölyesi', 'Atölyesi');",
  }),
  defineFunctionRef({
    slug: "concat-operatoru",
    ad: "|| (metin birleştirme)",
    kategori: "Metin",
    sozDizimi: "metin1 || metin2",
    aciklama: "İki (ya da daha fazla) metni birleştirir (concatenation) — SQLite'ta metin birleştirmenin standart yoludur.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT 'SQL' || ' ' || 'Atölyesi';",
    digerVeritabanlari: "MySQL/SQL Server'da (varsayılan ayarlarla) || yerine CONCAT() fonksiyonu kullanılır — bir sonraki kayda bak.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "concat",
    ad: "CONCAT",
    kategori: "Metin",
    sozDizimi: "CONCAT(metin1, metin2, ...) — SQLite'ta desteklenmez",
    aciklama: "Birden fazla metni birleştirir. DİKKAT: SQLite'ta CONCAT() fonksiyonu YOKTUR — bunun yerine || operatörü kullanılır.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT 'SQL' || ' ' || 'Atölyesi' AS concat_yerine;",
    ornekAciklama: "SQLite'ta CONCAT('SQL', ' ', 'Atölyesi') yazmaya çalışırsan hata alırsın; || kullanman gerekir.",
    digerVeritabanlari: "MySQL ve SQL Server'da CONCAT('a', 'b') doğrudan çalışır.",
  }),
  defineFunctionRef({
    slug: "left-fonksiyonu",
    ad: "LEFT",
    kategori: "Metin",
    sozDizimi: "LEFT(metin, n) — SQLite'ta desteklenmez",
    aciklama: "Bir metnin SOLUNDAN belirtilen sayıda karakteri alır. DİKKAT: SQLite'ta LEFT() fonksiyonu YOKTUR — aynı sonuç SUBSTR(metin, 1, n) ile elde edilir.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT SUBSTR('SQL Atölyesi', 1, 3) AS left_yerine;",
    digerVeritabanlari: "SQL Server ve MySQL'de LEFT('SQL Atölyesi', 3) doğrudan çalışır.",
  }),
  defineFunctionRef({
    slug: "right-fonksiyonu",
    ad: "RIGHT",
    kategori: "Metin",
    sozDizimi: "RIGHT(metin, n) — SQLite'ta desteklenmez",
    aciklama: "Bir metnin SAĞINDAN belirtilen sayıda karakteri alır. DİKKAT: SQLite'ta RIGHT() fonksiyonu YOKTUR — aynı sonuç SUBSTR(metin, -n) ile elde edilir (negatif baslangic sondan sayar).",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT SUBSTR('SQL Atölyesi', -8) AS right_yerine;",
    digerVeritabanlari: "SQL Server ve MySQL'de RIGHT('SQL Atölyesi', 8) doğrudan çalışır.",
  }),
  defineFunctionRef({
    slug: "printf",
    ad: "PRINTF",
    kategori: "Metin",
    sozDizimi: "PRINTF(format, deger, ...)",
    aciklama: "C dilindeki printf'e benzer şekilde, sayıları/metinleri belirli bir formatta biçimlendirir (ör. sıfır dolgulu sayılar, ondalık basamak sayısı).",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT PRINTF('%05d', 42);",
    ornekAciklama: "%05d, sayıyı 5 haneye tamamlayacak şekilde başına sıfır ekler.",
    digerVeritabanlari: "MySQL/SQL Server'da benzer işlev için FORMAT() kullanılır.",
  }),
];
