import { defineFunctionRef } from "@/types/content";
import { bosDb } from "@/content/databases/bos";

export const sayisalFonksiyonlar = [
  defineFunctionRef({
    slug: "round",
    ad: "ROUND",
    kategori: "Sayısal",
    sozDizimi: "ROUND(sayi, basamak)",
    aciklama: "Bir sayıyı belirtilen ondalık basamağa yuvarlar. basamak verilmezse tam sayıya yuvarlar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT ROUND(3.14159, 2), ROUND(3.7);",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "abs",
    ad: "ABS",
    kategori: "Sayısal",
    sozDizimi: "ABS(sayi)",
    aciklama: "Bir sayının mutlak değerini (işaretsiz halini) döndürür.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT ABS(-42);",
  }),
  defineFunctionRef({
    slug: "ceil",
    ad: "CEIL",
    kategori: "Sayısal",
    sozDizimi: "CEIL(sayi)",
    aciklama: "Sayıyı bir sonraki tam sayıya yukarı yuvarlar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT CEIL(4.2);",
    digerVeritabanlari: "MySQL/SQL Server'da CEILING() de kullanılabilir (SQLite'ta yalnızca CEIL çalışır, CEILING yoktur).",
  }),
  defineFunctionRef({
    slug: "floor",
    ad: "FLOOR",
    kategori: "Sayısal",
    sozDizimi: "FLOOR(sayi)",
    aciklama: "Sayıyı bir önceki tam sayıya aşağı yuvarlar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT FLOOR(4.8);",
  }),
  defineFunctionRef({
    slug: "mod-operatoru",
    ad: "% (MOD)",
    kategori: "Sayısal",
    sozDizimi: "sayi1 % sayi2",
    aciklama: "Bölme işleminden kalanı (mod) verir. DİKKAT: SQLite'ta MOD() fonksiyonu YOKTUR — % operatörü kullanılır.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT 17 % 5;",
    digerVeritabanlari: "MySQL/SQL Server'da hem % hem de MOD(17, 5) çalışır.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "power",
    ad: "POWER",
    kategori: "Sayısal",
    sozDizimi: "POWER(taban, us)",
    aciklama: "Bir sayının belirtilen kuvvetini (üssünü) hesaplar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT POWER(2, 10);",
  }),
  defineFunctionRef({
    slug: "sqrt",
    ad: "SQRT",
    kategori: "Sayısal",
    sozDizimi: "SQRT(sayi)",
    aciklama: "Bir sayının karekökünü hesaplar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT SQRT(144);",
  }),
  defineFunctionRef({
    slug: "random",
    ad: "RANDOM",
    kategori: "Sayısal",
    sozDizimi: "RANDOM()",
    aciklama:
      "Rastgele büyük bir tam sayı (pozitif ya da negatif) döndürür. Belirli bir aralıkta rastgele sayı üretmek için genelde ABS(RANDOM() % N) kalıbı kullanılır.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT ABS(RANDOM() % 100);",
    ornekAciklama: "0-99 arasında rastgele bir sayı üretir — her çalıştırdığında farklı bir sonuç göreceksin.",
  }),
  defineFunctionRef({
    slug: "max-min-skaler",
    ad: "MAX / MIN (skaler)",
    kategori: "Sayısal",
    sozDizimi: "MAX(deger1, deger2, ...) / MIN(deger1, deger2, ...)",
    aciklama:
      "DİKKAT: Bu, Toplulaştırma kategorisindeki GROUP BY ile kullanılan MAX/MIN'den FARKLIDIR — burada satırlar üzerinde değil, doğrudan verdiğin değerler arasından en büyüğü/en küçüğü seçilir.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT MAX(5, 12, 3) AS en_buyuk, MIN(5, 12, 3) AS en_kucuk;",
    ornekAciklama: "Toplulaştırma MAX(kolon) tablodaki satırlar arasından seçer; bu skaler form verdiğin sabit değerler arasından seçer.",
    oncelikli: true,
  }),
];
