import { defineFunctionRef } from "@/types/content";
import { bosDb } from "@/content/databases/bos";

export const tarihFonksiyonlari = [
  defineFunctionRef({
    slug: "date",
    ad: "DATE",
    kategori: "Tarih",
    sozDizimi: "DATE(zaman_degeri, [modifier, ...])",
    aciklama: "Bir zaman değerinden sadece tarih kısmını (YYYY-MM-DD) çıkarır.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT DATE('2025-06-15 14:30:00');",
  }),
  defineFunctionRef({
    slug: "time",
    ad: "TIME",
    kategori: "Tarih",
    sozDizimi: "TIME(zaman_degeri)",
    aciklama: "Bir zaman değerinden sadece saat kısmını (HH:MM:SS) çıkarır.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT TIME('2025-06-15 14:30:00');",
  }),
  defineFunctionRef({
    slug: "datetime",
    ad: "DATETIME",
    kategori: "Tarih",
    sozDizimi: "DATETIME(zaman_degeri)",
    aciklama: "Tarih ve saati birlikte (YYYY-MM-DD HH:MM:SS) döndürür.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT DATETIME('2025-06-15');",
  }),
  defineFunctionRef({
    slug: "strftime",
    ad: "STRFTIME",
    kategori: "Tarih",
    sozDizimi: "STRFTIME(format, zaman_degeri)",
    aciklama: "Bir tarihi istediğin özel formatta metne çevirir — %Y (yıl), %m (ay), %d (gün), %H (saat) gibi kalıplarla.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT STRFTIME('%Y-%m', '2025-06-15');",
    digerVeritabanlari: "MySQL'de benzer işlev DATE_FORMAT() ile, SQL Server'da FORMAT() ile yapılır.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "current-date",
    ad: "CURRENT_DATE",
    kategori: "Tarih",
    sozDizimi: "CURRENT_DATE",
    aciklama: "Bugünün tarihini (YYYY-MM-DD) döndürür — parantez almaz, doğrudan yazılır.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT CURRENT_DATE;",
  }),
  defineFunctionRef({
    slug: "current-timestamp",
    ad: "CURRENT_TIMESTAMP",
    kategori: "Tarih",
    sozDizimi: "CURRENT_TIMESTAMP",
    aciklama: "Şu anki tarih ve saati (UTC) döndürür.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT CURRENT_TIMESTAMP;",
  }),
  defineFunctionRef({
    slug: "julianday",
    ad: "JULIANDAY",
    kategori: "Tarih",
    sozDizimi: "JULIANDAY(zaman_degeri)",
    aciklama:
      "Bir tarihi 'Julian gün sayısı'na çevirir — iki tarih arasındaki gün farkını hesaplamanın standart yolu: iki JULIANDAY'i birbirinden çıkarırsın.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT JULIANDAY('2025-06-15') - JULIANDAY('2025-06-01') AS gun_farki;",
    digerVeritabanlari: "MySQL'de DATEDIFF(tarih1, tarih2), SQL Server'da DATEDIFF(day, tarih1, tarih2) kullanılır.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "tarih-aritmetigi",
    ad: "Tarih Aritmetiği (+/-)",
    kategori: "Tarih",
    sozDizimi: "DATE(tarih, '+N gün/ay/yıl')",
    aciklama: "DATE/DATETIME fonksiyonlarına bir 'modifier' metni ekleyerek tarihe gün/ay/yıl ekleyip çıkarabilirsin.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT DATE('2025-01-15', '+1 month', '-3 day');",
    ornekAciklama: "Aynı çağrıda birden fazla modifier art arda (soldan sağa) uygulanır.",
    digerVeritabanlari: "MySQL'de DATE_ADD(tarih, INTERVAL 1 MONTH), SQL Server'da DATEADD(month, 1, tarih) kullanılır.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "ayin-basi",
    ad: "start of (ay/yıl başı)",
    kategori: "Tarih",
    sozDizimi: "DATE(tarih, 'start of month')",
    aciklama: "'start of month' / 'start of year' gibi özel modifier'lar, bir tarihi içinde bulunduğu ayın ya da yılın ilk gününe yuvarlar.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT DATE('2025-06-15', 'start of month') AS ay_basi, DATE('2025-06-15', 'start of year') AS yil_basi;",
  }),
  defineFunctionRef({
    slug: "haftanin-gunu",
    ad: "Haftanın Günü",
    kategori: "Tarih",
    sozDizimi: "STRFTIME('%w', tarih)",
    aciklama: "Bir tarihin haftanın hangi gününe denk geldiğini 0 (Pazar) ile 6 (Cumartesi) arasında bir sayı olarak döndürür.",
    veritabaniId: bosDb.id,
    ornekSql: "SELECT STRFTIME('%w', '2025-06-15') AS haftanin_gunu;",
    digerVeritabanlari:
      "MySQL'de WEEKDAY() (0=Pazartesi), SQL Server'da DATEPART(weekday, ...) kullanılır — gün numaralandırması veritabanına göre değişir, dikkat et.",
  }),
];
