import { defineFunctionRef } from "@/types/content";
import { eticaretDb } from "@/content/databases/eticaret";

export const toplulastirmaFonksiyonlari = [
  defineFunctionRef({
    slug: "count",
    ad: "COUNT",
    kategori: "Toplulaştırma",
    sozDizimi: "COUNT(*) / COUNT(kolon)",
    aciklama: "COUNT(*) tüm satırları, COUNT(kolon) sadece o kolonu NULL OLMAYAN satırları sayar.",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT COUNT(*) AS toplam, COUNT(phone) AS telefonu_olan FROM customers;",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "sum",
    ad: "SUM",
    kategori: "Toplulaştırma",
    sozDizimi: "SUM(kolon)",
    aciklama: "Bir sayısal kolonun tüm değerlerinin toplamını hesaplar.",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT SUM(price) AS toplam_deger FROM products;",
  }),
  defineFunctionRef({
    slug: "avg",
    ad: "AVG",
    kategori: "Toplulaştırma",
    sozDizimi: "AVG(kolon)",
    aciklama: "Bir sayısal kolonun ortalamasını hesaplar.",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT AVG(price) AS ortalama_fiyat FROM products;",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "min-aggregate",
    ad: "MIN",
    kategori: "Toplulaştırma",
    sozDizimi: "MIN(kolon)",
    aciklama: "Bir kolondaki en küçük değeri bulur (sayısal ya da metin/tarih için alfabetik en küçük).",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT MIN(price) FROM products;",
  }),
  defineFunctionRef({
    slug: "max-aggregate",
    ad: "MAX",
    kategori: "Toplulaştırma",
    sozDizimi: "MAX(kolon)",
    aciklama: "Bir kolondaki en büyük değeri bulur.",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT MAX(price) FROM products;",
  }),
  defineFunctionRef({
    slug: "group-concat",
    ad: "GROUP_CONCAT",
    kategori: "Toplulaştırma",
    sozDizimi: "GROUP_CONCAT(kolon, ayrac)",
    aciklama: "Bir grup içindeki satırların değerlerini tek bir metinde (varsayılan olarak virgülle, istersen başka bir ayraçla) birleştirir.",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT category, GROUP_CONCAT(product_name, ' | ') AS urunler FROM products GROUP BY category;",
    ornekAciklama: "Her kategori için o kategorideki tüm ürün adlarını tek satırda görürsün.",
    digerVeritabanlari: "MySQL'de de GROUP_CONCAT() vardır (sözdizimi neredeyse aynı); SQL Server'da karşılığı STRING_AGG()'dir.",
    oncelikli: true,
  }),
  defineFunctionRef({
    slug: "total",
    ad: "TOTAL",
    kategori: "Toplulaştırma",
    sozDizimi: "TOTAL(kolon)",
    aciklama:
      "SUM()'a çok benzer, ama iki farkı var: hep REAL (ondalıklı) sonuç döndürür ve hiç satır yoksa (ya da hepsi NULL'sa) NULL yerine 0.0 döndürür — SUM boş bir grupta NULL verirdi.",
    veritabaniId: eticaretDb.id,
    ornekSql: "SELECT TOTAL(price) FROM products WHERE category = 'Olmayan Kategori';",
    ornekAciklama: "Hiç eşleşen satır olmadığı için SUM olsaydı NULL dönerdi; TOTAL 0.0 döndürür.",
    digerVeritabanlari: "TOTAL() SQLite'a özgüdür; MySQL/SQL Server'da bu davranış için genelde COALESCE(SUM(...), 0) yazılır.",
  }),
];
